# Generated by Django 5.1.7 on 2025-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('single', 'Single choice'), ('multiple', 'Multiple choices')], default='text', max_length=8),
        ),
    ]
